"""Administrative persistence port, implementable by a PostgreSQL adapter."""
from typing import Protocol
class AdminRepository(Protocol):
    def find_user(self,username): ...
    def create_user(self,data,actor,request_id,first=False): ...
    def change_user(self,identifier,data,actor,request_id,expected=None): ...
    def change_password(self,identifier,password_hash,actor,request_id): ...
    def open_session(self,user_id,password_hash,token_hash,csrf,now,inactivity,lifetime,request_id): ...
    def authorize(self,token_hash,now,inactivity): ...
    def revoke(self,token_hash,actor,request_id): ...
    def revoke_user(self,user_id,actor,request_id): ...
    def get_user(self,identifier): ...
    def audit(self,limit,offset,filters=None): ...
