"""Puerto de persistencia. Un adaptador PostgreSQL puede implementar este contrato."""
from typing import Protocol, ContextManager

class RepositoryConflict(ValueError):
    """Violación de unicidad o de una referencia; independiente del motor SQL."""

class ConfigurationUnit(Protocol):
    def list(self, resource: str) -> list[dict]: ...
    def get(self, resource: str, identifier: str) -> dict | None: ...
    def save(self, resource: str, identifier: str, data: dict, actor: str) -> dict: ...
    def settings(self) -> dict: ...
    def save_settings(self, data: dict, actor: str) -> None: ...
    def migration_applied(self, key: str) -> bool: ...
    def record_migration(self, key: str, fingerprint: str) -> None: ...

class ConfigurationRepository(Protocol):
    def transaction(self, *, write: bool = False) -> ContextManager[ConfigurationUnit]: ...
