"""Operational storage port. Business services do not depend on SQLite SQL."""
from typing import Protocol


class RuntimeConflict(Exception):
    def __init__(self, code='session_busy', status=409):
        self.code, self.status = code, status
        super().__init__(code)


class RuntimeRepository(Protocol):
    def create_session(self, session_id, token_hash): ...
    def authorize(self, session_id, token_hash): ...
    def begin(self, session_id, persona, replace=False, key=None): ...
    def current(self, session_id, request_id): ...
    def finish(self, session_id, request_id, question, answer, actions): ...
    def release(self, session_id, request_id): ...
    def cancel(self, session_id, request_id=None, reset=False, key=None): ...
    def cleanup(self): ...
    def health(self): ...
    def snapshot(self, session_id): ...
    def save_lead(self, session_id, data, key=None): ...
    def save_voucher(self, session_id, tariff, digest, key, write_file, remove_file, expected_lead=None, check_association=False): ...
    def get_record(self, kind, identifier): ...
    def backup(self, destination): ...

    def list_operational(self,kind,limit=100,offset=0,status=None): ...
    def administrative_counts(self): ...
    def review_voucher(self,identifier,status,note,actor,request_id): ...
    def admin_audit(self,limit=100,offset=0,filters=None): ...
